openapi: 3.0.0
info:
  version: 0.0-oas3
  title: cpuinfo
  description: >-
    A simple service to get cpuinfo as an example of using swagger-2.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /predict/{data}:
    get:
      tags:
        - PRED
      operationId: functions.my_prediction
      description: Returns cpu information of the hosting server
      parameters:
        - in: path
          name: data
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 12
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'CPU info, or add more text'
servers:
  - url: 'http://localhost:8080/engr-222'